config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "lists#index"
  resources :lists, only: [:index, :new, :create, :show, :destroy] do
    resources :bookmarks, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates_uniqueness_of :movie, scope: [:list]
  validates :comment, length: { minimum: 6 }

  # validates :name, uniqueness: { scope: :year,
  #   message: "should happen once per year" }
end

# A bookmark must be linked to a movie and a list, and the [movie, list] pairings should be unique.
# The comment of a bookmark cannot be shorter than 6 characters.

app/models/list.rb
class List < ApplicationRecord
  validates :name, uniqueness: true
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true
  has_one_attached :photo
  has_many :reviews, dependent: :destroy
end

# A list must have a unique name.

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, uniqueness: true
  validates :overview, uniqueness: true
  has_many :bookmarks
  validates :title, :overview, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
  RATINGS = (0..5).to_a.freeze
  validates :content, :rating, presence: true
  validates :rating, inclusion: { in: 0..5,
    message: '%{value} is not a valid review rating' }
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmarks_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = @bookmark.list
    @bookmark.destroy
    redirect_to list_path(@list)
  end

  private

  def bookmarks_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = Bookmark.all
  end

  def create
    @list = List.new(lists_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to root_path
  end


  private

  def lists_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @review = Review.new
  end

  def create
    @list = List.find(params[:list_id])
    @review = Review.new(reviews_params)
    @review.list = @list
    if @review.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def reviews_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/new.html.erb
<div class="container mt-3">
  <h1>Add a movie</h1>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie %>
    <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <%= render "shared/navbar"%>
  <div class="wrapper container">
    <%= yield %>
  </div>
  <%= render "shared/footer"%>
  </body>
</html>

app/views/lists/index.html.erb
<%= render "shared/home_banner"%>

<div class="container">
  <div class="d-flex justify-content-between mt-5">
    <h2>My lists</h2>
    <%= link_to "Add a new list", new_list_path, class: "btn btn-primary" %>
  </div>
  <div class = "d-flex justify-content-between align-content-around flex-wrap">
    <% @lists.each do |list| %>
      <% if list.photo.attached? %>
        <div class="card-category mt-5 delete-icon-parent" style="width: 18rem; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, height: 300, crop: :fill %>')">
          <%= link_to list.name, list_path(list), class: "card-text-white" %>
          <%= link_to list_path(list), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "delete-icon-child" do%>
            <i class="fa-regular fa-trash-can"></i>
          <% end %>
        </div>
      <% else %>
        <div class="card-category mt-5 delete-icon-parent" style="width: 18rem; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://img.freepik.com/free-vector/red-movie-theater-seats-with-curtains-background_1017-38388.jpg?w=2000')">
            <%= link_to list.name, list_path(list), class: "card-text-white" %>
            <%= link_to list_path(list), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "delete-icon-child" do%>
              <i class="fa-regular fa-trash-can"></i>
            <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<%# https://stackoverflow.com/questions/1137517/how-to-position-absolute-inside-a-div %>

app/views/lists/new.html.erb
<div class="container mt-3">
  <h1>Add a list</h1>
  <%= simple_form_for(@list) do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.submit %>
  <% end %>
</div>

app/views/lists/show.html.erb
<% if @list.photo.attached? %>
      <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @list.photo.key, height: 300, crop: :fill %>');">
        <div class="container">
          <h1 class="text-center"><%= @list.name %></h1>
        </div>
      </div>
    <% else %>
        <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://ichef.bbci.co.uk/news/976/cpsprodpb/18459/production/_117371499_gettyimages-1215359845.jpg);">
          <div class="container">
            <h1>Save all your favorite movies!</h1>
            <p>Organize your movies in lists</p>
          </div>
        </div>
      </div>
<% end %>

<div class="container">
  <div class="d-flex flex-row-reverse mt-5">
      <%= link_to "Add a movie", new_list_bookmark_path(@list), class: "btn btn-primary mx-3" %>
      <%= link_to "Add a review", new_list_review_path(@list), class: "btn btn-primary mx-3" %>
  </div>
  <div class = "d-flex justify-content-between align-content-around flex-wrap">
    <% @bookmarks.each do |bookmark|%>
      <% if bookmark.list_id == @list.id  %>
        <div class="card mt-5" style="width: 18rem;">
          <img class="card-img-top" src="<%= bookmark.movie.poster_url %>" alt="Card image cap">
          <div class="card-body d-flex flex-column">
            <div class="d-flex justify-content-between">
              <h5 class="card-title"><%= bookmark.movie.title %></h5>
              <div>
                <i class="fa-regular fa-star"></i>
                <%= bookmark.movie.rating %>
              </div>
            </div>
            <p class="card-text text-limit"><%= bookmark.movie.overview %></p>
            <div class="d-flex justify-content-between">
              <div>
                <i class="fa-solid fa-quote-left"></i>
                <%= bookmark.comment %>
              </div>
              <%= link_to "delete", bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "delete-link" %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class= "mt-5">
    <h3><strong>Reviews</strong></h3>
    <ul class="list-group mt-3">
    <% if @list.reviews.length == 0 %>
      <li class="list-group-item">No ratings for now</li>
    <% else %>
      <% @list.reviews.each do |review| %>
        <li class="list-group-item"><%= review.rating %>/5: <%= review.content %></li>
      <% end %>
    <% end %>
    </ul>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container mt-3">
  <h1>Add a review for <%= @list.name %> movie list</h1>
  <%= simple_form_for [@list, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating, collection: Review::RATINGS %>
    <%= f.submit "Submit review", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/shared/_footer.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/FabrizioDurand" target="_blank"><i class="fab fa-github"></i></a>
    <a href="https://www.linkedin.com/in/fabrizio-durand-19264b97" target="_blank"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer was made with <i class="fas fa-heart"></i>
  </div>
</div>

app/views/shared/_home_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://ichef.bbci.co.uk/news/976/cpsprodpb/18459/production/_117371499_gettyimages-1215359845.jpg);">
  <div class="container">
    <h1>Save all your favorite movies!</h1>
    <p>Organize your movies in lists</p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://cdn-icons-png.flaticon.com/512/184/184578.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "My lists", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "New list", new_list_path, class: "nav-link" %>
          </li>
      </ul>
    </div>
  </div>
</div>